### ISSUE TITLE
total run-time?

### ISSUE THREAD

**Issue by alenamois** [MWransky/dialogue-gan#1]
Hi! I would like to ask, what is the typical total run-time for a CPU and a GPU?
Besides that:
I am currently training a generator model and it already runs for 3 days. Perplexity gets lower, but training does not end. Is it ok? Also in 'the train-gen' (line:114) model there is a while loop, which is always True and there is no explicit break within the loop. Can it cause the 'endless' training?
Thanks in advance for your feedback and help!

**Comment by MWransky** [comment]
Hi @alenamois thanks for your questions! From my experience, running on a GPU is about 10x faster than on a CPU. For decent results from the model I've run things on a GPU for around 2 days. That was using the cornell movie dialog dataset. 

I purposefully made the training loop infinite because I tend to watch how the perplexity and such changes and then make a decision on when to stop. Left untouched it will run endlessly. The model gets saved every so many iterations so you are probably good to stop the script from running whenever you are ready.

**Comment by alenamois** [comment]
Thanks a lot for the detailed answer! 
It helped me a lot!
